language: go
go:
  - 1.9.2
sudo: false
branches:
  only:
    - master
env:
  global:
    - SOURCE_DIR="public"
    - BUILD_BRANCH="source"
    - DEPLOY_BRANCH="master"

install:
  - go get -u -v github.com/spf13/hugo

script:
  - hugo

deploy:
  - provider: pages
    edge: true
    github_token: ${GITHUB_TOKEN}
    local_dir: public
    skip_cleanup: true
    repo: albee824/albee824.github.io
    on:
      branch: master